development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  timeout: 5000
  username: erik
  password: ubuntu

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  timeout: 5000
  username: erik
  password: ubuntu
